# DSpace Continuous Integration/Build via GitHub Actions
# Concepts borrowed from
# https://docs.github.com/en/free-pro-team@latest/actions/guides/building-and-testing-nodejs
name: Build

# Run this Build for all pushes / PRs to current branch
on: [push, pull_request]

permissions:
  contents: read  # to fetch code (actions/checkout)
  packages: read  # to fetch private images from GitHub Container Registry (GHCR)

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      # The ci step will test the dspace-angular code against DSpace REST.
      # Direct that step to utilize a DSpace REST service that has been started in docker.
      # NOTE: These settings should be kept in sync with those in [src]/docker/docker-compose-ci.yml
      DSPACE_REST_HOST: 127.0.0.1
      DSPACE_REST_PORT: 8080
      DSPACE_REST_NAMESPACE: '/server'
      DSPACE_REST_SSL: false
      # Spin up UI on 127.0.0.1 to avoid host resolution issues in e2e tests with Node 18+
      DSPACE_UI_HOST: 127.0.0.1
      DSPACE_UI_PORT: 4000
      # Ensure all SSR caching is disabled in test environment
      DSPACE_CACHE_SERVERSIDE_BOTCACHE_MAX: 0
      DSPACE_CACHE_SERVERSIDE_ANONYMOUSCACHE_MAX: 0
      # Tell Cypress to run e2e tests using the same UI URL
      CYPRESS_BASE_URL: http://127.0.0.1:4000
      # Disable the cookie consent banner in e2e tests to avoid errors because of elements hidden by it
      DSPACE_INFO_ENABLECOOKIECONSENTPOPUP: false
      # When Chrome version is specified, we pin to a specific version of Chrome
      # Comment this out to use the latest release
      #CHROME_VERSION: "90.0.4430.212-1"
      # Bump Node heap size (OOM in CI after upgrading to Angular 15)
      NODE_OPTIONS: '--max-old-space-size=4096'
      # Project name to use when running "docker compose" prior to e2e tests
      COMPOSE_PROJECT_NAME: 'ci'
      # Docker Registry to use for Docker compose scripts below.
      # We use GitHub's Container Registry to avoid aggressive rate limits at DockerHub.
      DOCKER_REGISTRY: ghcr.io
    strategy:
      # Create a matrix of Node versions to test against (in parallel)
      matrix:
        node-version: [18.x]
      # Do NOT exit immediately if one matrix job fails
      fail-fast: false
    # These are the actual CI steps to perform per job
    steps:
      # https://github.com/actions/checkout
      - name: Checkout codebase
        uses: actions/checkout@v4

      # https://github.com/actions/setup-node
      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      # If CHROME_VERSION env variable specified above, then pin to that version.
      # Otherwise, just install latest version of Chrome.
      - name: Install Chrome (for e2e tests)
        run: |
          if [[ -z "${CHROME_VERSION}" ]]
          then
             echo "Installing latest stable version"
             sudo apt-get update
             sudo apt-get --only-upgrade install google-chrome-stable -y
          else
             echo "Installing version ${CHROME_VERSION}"
             wget -q "https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_${CHROME_VERSION}_amd64.deb"
             sudo dpkg -i "google-chrome-stable_${CHROME_VERSION}_amd64.deb"
          fi
          google-chrome --version

      # https://github.com/actions/cache/blob/main/examples.md#node---yarn
      - name: Get Yarn cache directory
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT
      - name: Cache Yarn dependencies
        uses: actions/cache@v4
        with:
          # Cache entire Yarn cache directory (see previous step)
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          # Cache key is hash of yarn.lock. Therefore changes to yarn.lock will invalidate cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-

      - name: Install Yarn dependencies
        run: yarn install --frozen-lockfile

      - name: Build lint plugins
        run: yarn run build:lint

      - name: Run lint plugin tests
        run: yarn run test:lint:nobuild

      - name: Run lint
        run: yarn run lint:nobuild --quiet

      - name: Check for circular dependencies
        run: yarn run check-circ-deps

      - name: Run build
        run: yarn run build:prod

      - name: Run specs (unit tests)
        run: yarn run test:headless

      # Upload code coverage report to artifact (for one version of Node only),
      # so that it can be shared with the 'codecov' job (see below)
      # NOTE: Angular CLI only supports code coverage for specs. See https://github.com/angular/angular-cli/issues/6286
      - name: Upload code coverage report to Artifact
        uses: actions/upload-artifact@v4
        if: matrix.node-version == '18.x'
        with:
          name: coverage-report-${{ matrix.node-version }}
          path: 'coverage/dspace-angular/lcov.info'
          retention-days: 14

      # NOTE: e2e tests, SSR verification and Docker backend steps have been removed.
      # This fork does not have a DSpace REST backend Docker image configured for CI.
